### ISSUE TITLE
Firefox: can only play

### ISSUE THREAD

**Issue by yarekc** [hxtmr/live#2]
Hi,
- Looks like Firefox can only play the video, but cannot push.

- Chrome can both push and pull

Any chance to make it work on Firefox ?

**Comment by maxianbin** [comment]
firefox do not support   mimeType vp9,opus yet，I added vp8,opus type for firefox in the new code ,please checkout the newest code. 
have a nice day ^_^

**Comment by yarekc** [comment]
Thanks I saw you changed: 

```
if (headerTag.equals(vp9Header)) {
            console.log('vp9')
            isHeader = true;
            app.sourceBufferType = 'video/webm;codecs=vp9,opus'
            videoHeader = buffer.slice(0, 189)
        } else if (headerTag.equals(vp8Header)) {//#2  Firefox: can only play
            console.log('vp8')
            isHeader = true
            app.sourceBufferType = 'video/webm;codecs=vp8,opus'
            videoHeader = buffer.slice(0, 313)
        }
```

**From what I know:** 
Chrome->chrome : OK
Chrome->FF: OK
FF->FF : OK
FF->Chrome: KO. This works Only if firefox  disables audio :

navigator.mediaDevices.getUserMedia( {audio: false, video: true})

Have you tested ALL these cases ?

PS. are you enable/free for paid freelancer task ?

Regards
